# Generated by Django 5.1.1 on 2024-10-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_email', models.EmailField(max_length=254)),
                ('inf_text', models.CharField(max_length=250)),
                ('tel', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Social_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
