# Generated by Django 5.1.1 on 2024-10-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, default=True, max_digits=4, null=True),
        ),
    ]
