# Generated by Django 5.1.1 on 2024-11-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='catr',
            new_name='cart',
        ),
    ]
