# Generated by Django 5.1.1 on 2024-11-10 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_catr_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('ashgabat', 'Ashgabat saheri'), ('arkadag', 'Arkadag saheri'), ('mary', 'Mary saheri'), ('dashoguz', 'Dashoguz saheri'), ('lebap', 'Lebap Saheri'), ('balkan', 'Balkan saheri')], max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('order_status', models.CharField(choices=[('ordered', 'Ordered'), ('panding', 'Panding'), ('sended', 'Sended'), ('delivered', 'Delivered')], max_length=20)),
                ('payment_type', models.CharField(choices=[('card', 'By Card'), ('cash', 'By Cash')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='main.cart')),
            ],
        ),
    ]
